-- =============================================================
-- INSURANCE_REGULATORY.REFERENCE.TSPR_VALIDATION_RULES
-- Jurisdiction scope: US-TX ∪ US (federal defaults)
-- Generated by scripts.build_validation_rules_reference from the RegulAI KG.
-- =============================================================

USE DATABASE INSURANCE_REGULATORY;
USE SCHEMA REFERENCE;

CREATE OR REPLACE TABLE TSPR_VALIDATION_RULES (
    rule_id              VARCHAR(64)  NOT NULL,
    rule_number          VARCHAR(32)  NOT NULL,
    rule_name            VARCHAR(512) NOT NULL,
    section              VARCHAR(8),
    jurisdiction_code    VARCHAR(8)   NOT NULL DEFAULT 'US-TX',
    is_federal_default   BOOLEAN      NOT NULL DEFAULT FALSE,
    target_table         VARCHAR(128) NOT NULL,
    target_id_expr       VARCHAR(1024),
    violation_sql        VARCHAR(8000) NOT NULL,
    violation_reason     VARCHAR(1024) NOT NULL,
    severity             VARCHAR(16)   NOT NULL,
    citation             VARCHAR(1024),
    validation_version   NUMBER(10,0)  NOT NULL,
    kg_canon_version     NUMBER(10,0),
    kg_source_document_id VARCHAR(64),
    generated_at         TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT pk_tspr_validation_rules PRIMARY KEY (rule_id)
) COMMENT = 'Executable validation rules. Sourced from RegulAI KG, scoped by jurisdiction.';

-- Replace only this jurisdiction's rows so multi-jurisdiction loads accumulate safely.
DELETE FROM TSPR_VALIDATION_RULES WHERE jurisdiction_code = 'US-TX';
DELETE FROM TSPR_VALIDATION_RULES WHERE jurisdiction_code = 'US';

-- A.34-valid-codes: Reason codes must be defined in the plan  (scope=US-TX)
INSERT INTO TSPR_VALIDATION_RULES (
    rule_id, rule_number, rule_name, section, jurisdiction_code, is_federal_default, target_table, target_id_expr, violation_sql, violation_reason, severity, citation, validation_version, kg_canon_version, kg_source_document_id, generated_at
) VALUES (
    '287871fa-72fc-4a42-8300-9377d69e97db-validity', 'A.34-valid-codes', 'Reason codes must be defined in the plan', 'A', 'US-TX', FALSE, 'BRONZE.GW_PC_JOB', 'j.publicid', 'COALESCE(j.declinereason, j.cancellationreason, j.nonrenewalreason) IS NOT NULL
            AND NOT COALESCE(j.declinereason, j.cancellationreason, j.nonrenewalreason) RLIKE
              ''^('' || (
                SELECT LISTAGG(tspr_reason_code, ''|'') WITHIN GROUP (ORDER BY tspr_reason_code)
                FROM INSURANCE_REGULATORY.REFERENCE.TSPR_REASON_CODE_MAP
              ) || '')+$''', 'One or more reason letters are not part of the published Reason Code List', 'ERROR', 'TICO Stat Plan Rule A.34 / Section E', 1, 1, NULL, CURRENT_TIMESTAMP()
);

-- Verification
SELECT jurisdiction_code, severity, COUNT(*) AS n FROM TSPR_VALIDATION_RULES GROUP BY 1, 2 ORDER BY 1, 2;